spring:
  # thymleaf??
  thymeleaf:
    # ????
    cache: false
    # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 111111

    #hikari:
      # ????
      #pool-name:  DateHikariCP
      # ???????
      #minimum-idle: 5
      # ???????????????10min
      #idle-timeout: 18000
      # ????????10
      #maximum-pool-size: 10
      # ?????????????
      #auto-commit: true
      # ???????????30??
      #max-lifetime: 1800000
      # ?????????30s
      #connection-timeout: 30000
      # ????????????
      #connection-test-query: SELECT 1

#Mybatis-plus??
#mybatis-plus:
  #??mapper.xml????
  #mapper-locations: classpath*:/mapper/*Mapper.xml
  #type-aliases-package: com.example.seckill.pojo

# Mybatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.example.seckill.mapper: debug
