spring:
  #静态资源处理
  resource:
    #启用默认静态资源处理，默认启用
    cache:
      cachecontrol:
        #缓存响应时间，单位是秒
        max-age: 3600
    chain:
      #资源链启用缓存，默认启用
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源（gzip，brotli）解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
  # thymleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 111111
    hikari:
      # ????
      pool-name:  DateHikariCP
      # ???????
      minimum-idle: 5
      # ???????????????10min
      idle-timeout: 18000
      # ????????10
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ???????????30??
      max-lifetime: 1800000
      # ?????????30s
      connection-timeout: 30000
      # ????????????
      connection-test-query: SELECT 1

  #redis配置
  redis:
    #服务器地址
    host: 192.168.93.132
    #端口
    port: 6379
    #数据库
    database: 0
    #连接超时时间
    timeout: 10000s
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大等待时间，或者叫最大链接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

#Mybatis-plus配置
mybatis-plus:
  #配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.seckill.pojo

# Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.example.seckill.mapper: debug
